# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFCreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PDFCreator

  target 'PDFCreatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PDFCreatorUITests' do
    # Pods for testing
  end
  pod 'DynamsoftDocumentNormalizerBundle','2.2.1100'
end
