# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFCreator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PDFCreator

  target 'PDFCreatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PDFCreatorUITests' do
    # Pods for testing
  end
  pod 'DynamsoftCaptureVisionRouter','2.2.30'
  pod 'DynamsoftCore','3.2.30'
  pod 'DynamsoftDocumentNormalizer','2.2.11'
  pod 'DynamsoftImageProcessing','2.2.30'
  pod 'DynamsoftLicense','3.2.20'
  pod 'DynamsoftUtility','1.2.20'
end
